import { Router } from 'express';
import authRoutes from './authRoutes';
import employeeRoutes from './employeeRoutes';
import sectionRoutes from './sectionRoutes';
import flowRoutes from './flowRoutes';
import shiftRoutes from './shiftRoutes';
import attendanceRoutes from './attendanceRoutes';
import gpsRoutes from './gpsRoutes';
import breakRoutes from './breakRoutes';
import reportRoutes from './reportRoutes';
import securityRoutes from './securityRoutes';
import auditRoutes from './auditRoutes';
import settingsRoutes from './settingsRoutes';
import eventTypeRoutes from './eventTypeRoutes';
import adminRoutes from './adminRoutes';
import notificationRoutes from './notificationRoutes';
import uploadRoutes from './uploadRoutes';
import dashboardRoutes from './dashboardRoutes';
import { apiLimiter } from '../middleware/rateLimiter';

const router = Router();
router.use(apiLimiter);
router.use('/auth', authRoutes);
router.use('/employees', employeeRoutes);
router.use('/sections', sectionRoutes);
router.use('/flows', flowRoutes);
router.use('/shifts', shiftRoutes);
router.use('/attendance', attendanceRoutes);
router.use('/gps', gpsRoutes);
router.use('/breaks', breakRoutes);
router.use('/reports', reportRoutes);
router.use('/security', securityRoutes);
router.use('/audit', auditRoutes);
router.use('/settings', settingsRoutes);
router.use('/event-types', eventTypeRoutes);
router.use('/admin', adminRoutes);
router.use('/notifications', notificationRoutes);
router.use('/upload', uploadRoutes);
router.use('/dashboard', dashboardRoutes);

export default router;
